In [1]:
import numpy as np
go_embs = np.load('/home/ukjung18/GIE1/GIE/GIE-master/LOG_DIR/08_21/GO0818/MurP_08_58_37/entity_embedding.npy')

In [2]:
import pandas as pd
goa_df = pd.read_csv('/home/ukjung18/GIE1/GIE/GIE-master/src_data/GO0818/full_goa_edges.tsv', sep='\t')
goa_df

head               rel        tail
0       A0A024RBG1       goa_enables  GO:0000298
1       A0A024RBG1       goa_enables  GO:0003723
2       A0A024RBG1       goa_enables  GO:0008486
3       A0A024RBG1       goa_enables  GO:0034431
4       A0A024RBG1       goa_enables  GO:0034432
...            ...               ...         ...
287848      U3KPV4   goa_involved_in  GO:0006688
287849      U3KPV4   goa_involved_in  GO:0030259
287850      U3KPV4  goa_is_active_in  GO:0005794
287851      U3KPV4  goa_is_active_in  GO:0031982
287852      U3KPV4    goa_located_in  GO:0032580

[287853 rows x 3 columns]

In [3]:
go_df = pd.read_csv('/home/ukjung18/GIE1/GIE/GIE-master/src_data/GO0818/entities.tsv', sep='\t')
go_df

term  level               class
0      GO:0000001      5  biological_process
1      GO:0000002      6  biological_process
2      GO:0000003      1  biological_process
3      GO:0000006      5  molecular_function
4      GO:0000007      5  molecular_function
...           ...    ...                 ...
42945  GO:2001313      4  biological_process
42946  GO:2001314      5  biological_process
42947  GO:2001315      5  biological_process
42948  GO:2001316      4  biological_process
42949  GO:2001317      5  biological_process

[42950 rows x 3 columns]

In [4]:
go_dict = {}
for i, row in go_df.iterrows():
    go_dict[row['term']] = i
len(go_dict)

42950

In [5]:
goa_dict = {}
for _, row in goa_df.iterrows():
    if row['head'] not in goa_dict.keys():
        goa_dict[row['head']] = [row['tail']]
    else:
        goa_dict[row['head']].append(row['tail'])

In [6]:
prot = 'A0A024RBG1'
go_list = goa_dict[prot]
go_list

['GO:0000298',
 'GO:0003723',
 'GO:0008486',
 'GO:0034431',
 'GO:0034432',
 'GO:0046872',
 'GO:0071543',
 'GO:1901907',
 'GO:1901909',
 'GO:1901911',
 'GO:0005634',
 'GO:0005737',
 'GO:0005829']

In [7]:
prot_embs = {}
for prot, go_list in goa_dict.items():
    emb_list = [go_embs[go_dict[go]] for go in go_list]
    emb_sum = np.sum(emb_list, axis=0)
    prot_embs[prot] = emb_sum

In [8]:
len(prot_embs)

18133

In [9]:
prot_embs['A0A024RBG1'].shape

(300,)

In [10]:
import pickle
with open('/home/ukjung18/HiG2Vec/evalGene/prot_dict.pickle','rb') as fw:
    prot_to_id = pickle.load(fw)

In [11]:
import numpy as np
entity_embs = np.empty([300])
for term, i in prot_to_id.items():
    entity_embs = np.vstack((entity_embs, prot_embs[term]))
entity_embs = np.delete(entity_embs, (0), axis=0)
entity_embs.shape

(18133, 300)

In [13]:
np.save('/home/ukjung18/anc2vec/examples/murp_embeddings.npy', entity_embs)

In [10]:
import numpy as np
rot_path = '/home/ukjung18/GIE1/GIE/GIE-master/LOG_DIR/08_07/GOA0723/GIE_rot_13_34_31/test_attention_weights.npy'
ref_path = '/home/ukjung18/GIE1/GIE/GIE-master/LOG_DIR/08_07/GOA0723/GIE_ref_13_34_35/test_attention_weights.npy'
trans_path = '/home/ukjung18/GIE1/GIE/GIE-master/LOG_DIR/08_07/GOA0723/GIE_trans_13_34_38/test_attention_weights.npy'
val_rot_path = '/home/ukjung18/GIE1/GIE/GIE-master/LOG_DIR/08_07/GOA0723/GIE_rot_13_34_31/valid_attention_weights.npy'
val_ref_path = '/home/ukjung18/GIE1/GIE/GIE-master/LOG_DIR/08_07/GOA0723/GIE_ref_13_34_35/valid_attention_weights.npy'
val_trans_path = '/home/ukjung18/GIE1/GIE/GIE-master/LOG_DIR/08_07/GOA0723/GIE_trans_13_34_38/valid_attention_weights.npy'
rot_att = np.load(rot_path)
ref_att = np.load(ref_path)
trans_att = np.load(trans_path)
val_rot_att = np.load(val_rot_path)
val_ref_att = np.load(val_ref_path)
val_trans_att = np.load(val_trans_path)

In [11]:
rot_att[-1]

array([[0.3963412 ],
       [0.32492194],
       [0.27873686]])

In [13]:
val_rot_att.shape

(68, 3, 1)

In [4]:
ref_att[-1]

array([[0.29928053],
       [0.23803252],
       [0.46268695]])

In [6]:
trans_att[0]

array([[0.31217413],
       [0.31217413],
       [0.37565175]])