In [1]:
import torch
import numpy as np
from numpy import random
from torch import nn

In [16]:
def givens_rotations(r, x):
    givens = r.view((r.shape[0], -1, 2))
    givens = givens / torch.norm(givens, p=2, dim=-1, keepdim=True).clamp_min(1e-15)
    x = x.view((r.shape[0], -1, 2))
    x_rot = givens[:, :, 0:1] * x + givens[:, :, 1:] * torch.cat((-x[:, :, 1:], x[:, :, 0:1]), dim=-1)
    return x_rot.view((r.shape[0], -1))

In [17]:
rel_diag = nn.Embedding(5, 4)
rel_diag.weight.data = 2 * torch.rand((5, 4), dtype=torch.double) - 1.0
rel_diag

Embedding(5, 4)

In [18]:
lhs = nn.Embedding(3, 4)
lhs.weight.data = torch.randn((3, 4), dtype=torch.double)
lhs

Embedding(3, 4)

In [25]:
r= rel_diag(torch.tensor([1]))
r

tensor([[-0.5334,  0.9108,  0.0470,  0.6168]], dtype=torch.float64,
       grad_fn=<EmbeddingBackward0>)

In [27]:
givens = r.view((r.shape[0], -1, 2))
givens

tensor([[[-0.5334,  0.9108],
         [ 0.0470,  0.6168]]], dtype=torch.float64, grad_fn=<ViewBackward0>)

In [32]:
givens = givens / torch.norm(givens, p=2, dim=-1, keepdim=True).clamp_min(1e-15)
givens.shape

torch.Size([1, 2, 2])

In [33]:
x = lhs(torch.tensor([1]))
x = x.view((r.shape[0], -1, 2))
x.shape

torch.Size([1, 2, 2])

In [31]:
givens[:,:,0:1]

tensor([[[-0.5053],
         [ 0.0760]]], dtype=torch.float64, grad_fn=<SliceBackward0>)

In [ ]:
x_rot = givens[:, :, 0:1] * x + givens[:, :, 1:] * torch.cat((-x[:, :, 1:], x[:, :, 0:1]), dim=-1)

In [ ]:
x_rot.view((r.shape[0], -1))