In [2]:
import torch
x = torch.rand((4,1))
x

tensor([[0.2266],
        [0.4430],
        [0.3752],
        [0.4458]])

In [3]:
torch.sqrt(x)

tensor([[0.4760],
        [0.6656],
        [0.6125],
        [0.6677]])

In [2]:
x = torch.nn.Embedding(3,2)
x

Embedding(3, 2)

In [8]:
x(torch.tensor([0,1]))

tensor([[-0.9525,  1.0014],
        [-0.1952,  0.0773]], grad_fn=<EmbeddingBackward0>)

In [16]:
x.weight[torch.tensor([0,1])]

tensor([[-0.9525,  1.0014],
        [-0.1952,  0.0773]], grad_fn=<IndexBackward0>)

In [13]:
phase_head, mod_head = torch.chunk(x.weight, 2, dim=1)

In [14]:
phase_head

tensor([[-0.9525],
        [-0.1952],
        [-0.5296]], grad_fn=<SplitBackward0>)

In [7]:
torch.sum(x(torch.tensor([1])) * x(torch.tensor([1])), dim=-1, keepdim=True)

tensor([[0.7597]], grad_fn=<SumBackward1>)

In [11]:
y = torch.nn.Embedding(5,2)
y

Embedding(5, 2)

In [12]:
x(torch.tensor([1])) @ (y.weight).t()

tensor([[ 1.1525,  0.8755, -1.5320, -0.3808,  0.3339]], grad_fn=<MmBackward0>)

In [5]:
x.weight.data

tensor([[-1.0594, -1.6583],
        [-0.4011, -0.7738],
        [ 0.1624, -1.3112]])

In [10]:
y = torch.nn.Parameter(torch.rand((3,2)))
y

Parameter containing:
tensor([[0.8504, 0.5159],
        [0.8731, 0.5559],
        [0.4402, 0.2011]], requires_grad=True)

In [18]:
x(torch.tensor([0,1]))

tensor([[-0.0465,  0.0342],
        [ 1.1580,  0.1436]], grad_fn=<EmbeddingBackward0>)

In [15]:
y[[0,1]]

tensor([[0.8504, 0.5159],
        [0.8731, 0.5559]], grad_fn=<IndexBackward0>)

In [20]:
z=torch.chunk(y, 2, dim=1)
z

(tensor([[0.8504],
         [0.8731],
         [0.4402]], grad_fn=<SplitBackward0>),
 tensor([[0.5159],
         [0.5559],
         [0.2011]], grad_fn=<SplitBackward0>))